language : go 

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - go get github.com/constabulary/gb/...
  - go get -u github.com/ains/go-test-html
  - go get -u github.com/tools/godep/...
install:  
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling.git
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling
  - godep restore
  - go test ./... -v 2> >(tee gotest_stderr_file) | tee gotest_stdout_file
  - make all
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone -b gotest https://github.com/LakshmiMekala/remoterecipes.git remoterecipes
  - pushd remoterecipes/go-test
script:  
  - chmod ugo+x ./report-copy.sh
  - ./report-copy.sh
  - popd
  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
  
# addons:
#   artifacts:
#     # ...
#     paths:
#     - $(git ls-files -o | tr "\n" ":")