language : go 

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - go get github.com/constabulary/gb/...
  - go get -u github.com/ains/go-test-html
  - go get -u github.com/tools/godep/...
install:  
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling.git
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling
  - godep restore
  - go test ./... -v 2> >(tee gotest_stderr_file) | tee gotest_stdout_file
  - go-test-html gotest_stdout_file gotest_stderr_file go-test-result.html
  - make all
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone -b gotests https://github.com/LakshmiMekala/remoterecipes.git remoterecipes
  - cd remoterecipes/go-test
script:  
  - chmod ugo+x ./report.sh
  - ./report.sh
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
# deploy:
#   provider: s3
#   access_key_id: $SITE_KEY
#   secret_access_key: $SITE_KEY_SECRET
#   bucket: $AWS_BUCKET
#   region: $AWS_REGION
#   skip_cleanup: true
#   on:
#     all_branches: true
#   local_dir: $GOPATH/src/github.com/TIBCOSoftware/recip1/samples-recipes/master-builds
#   upload-dir: master-builds
  
addons:
  artifacts:
    # ...
    #working_dir: $GOPATH/src/github.com/TIBCOSoftware/mashling/$destFolder
    paths:
    - $(git ls-files -o | tr "\n" ":")