language : go 
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - go get github.com/constabulary/gb/...
  - go get -u github.com/ains/go-test-html
  - go get -u github.com/tools/godep/...
  - sudo apt-add-repository ppa:duggan/jo --yes
  - sudo apt-get update -q
  - sudo apt-get install jo
  - pip install --user awscli
install:  
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling.git
  - git clone https://github.com/LakshmiMekala/sampleabc.git mashling-recipes
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling
  - godep restore
  - make all
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone -b sanity-tests https://github.com/LakshmiMekala/remoterecipes.git recip1
  - pushd recip1/samples-recipes
  - mkdir -p master-builds/latest/temp builds/latest
script:  
  - chmod ugo+x ./final-remoteurl.sh ./sanity-test.sh
  - ./final-remoteurl.sh OPTIMIZE=$BUILDFLAGVALUE;
  - ./sanity-test.sh
  - popd
  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
  - "[ -f \"${HOME}/.aws\" ] && rm -f ${HOME}/.aws"
