language : go 

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
#  - pip install --user awscli
install:
  - go get github.com/constabulary/gb/...
  - sudo apt-add-repository ppa:duggan/jo --yes
  - sudo apt-get update -q
  - sudo apt-get install jo
  - go get -u github.com/TIBCOSoftware/mashling/...
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/LakshmiMekala/sampleabc.git mashling-recipes
  - git clone https://github.com/LakshmiMekala/remoterecipes.git recip1
  - pushd recip1/samples-recipes
  - rm -rf master-builds 
  - mkdir -p master-builds/latest/temp builds/latest
  
script:
   - chmod ugo+x ./addremote-url.sh ./as2.sh
   - ./addremote-url.sh
  # - ./latest.sh OPTIMIZE=${BUILDFLAGVALUE}
  # - ./as2.sh
   - popd
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
#  - "[ -f \"${HOME}/.aws\" ] && rm -f ${HOME}/.aws"
# deploy:
#   provider: s3
#   access_key_id: $SITE_KEY
#   secret_access_key: $SITE_KEY_SECRET
#   bucket: $AWS_BUCKET
#   region: $AWS_REGION
#   skip_cleanup: true
#   on:
#     all_branches: true
#   local_dir: $GOPATH/src/github.com/TIBCOSoftware/recip1/samples-recipes/master-builds
#   upload-dir: master-builds
  
